#destination: ./michaelchelen.net
highlighter: pygments
markdown: rdiscount
exclude: [mkdocument]
lsi: true
permalink: /:shortid/:title/
# leave blank for /
url_root: 
# Options used in Jekyll-base
#base_dir: /michaelchelen.net
#ga_id: UA_XXXXXXXX-1
#google_search_api_key: 1238975398735
#google_search_site_url: fastr.github.com
#title_prefix: 
gems:
  - jekyll-redirect-from
